module.exports = {
	'Test max' : function(browser){
		browser
			.url('http://localhost:3000/order')
			.pause(200)
			.click('#menuButton1')
			.pause(200)
			.click('#addButton-3')
			.pause(200)
			.click('#menuButton2')
			.pause(200)
			.click('#addButton-12')
			.click('#menuButton3')
			.pause(200)
			.click('#addButton-10')
			.click('#menuButton1')
			.pause(100)
			.click('#addButton-2')
			.pause(200)
			.click('#addButton-4')
			.pause(200)
			.click('#addButton-5')
			.pause(200)
			.click('#addButton-6')
			.pause(200)
			.click('#addButton-1')
			.pause(200)
			.click('#menuButton2')
			.pause(100)
			.click('#addButton-18')
			.click('#addButton-7')
			.click('#menuButton3')
			.pause(1000)
			.click('#addButton-9')
			.pause(1000)
			.assert.containsText('#errorMessage', 'Max number of items reached')

			.end()
	}
}